export const tintas = [
  { label: "Amarillo GCMI 10", value: "Amarillo GCMI 10" },
  { label: "Amarillo GCMI 13", value: "Amarillo GCMI 13" },
  { label: "Azul 298 C", value: "Azul 298 C" },
  { label: "Azul 38 BONDY", value: "Azul 38 BONDY" },
  { label: "Azul 394", value: "Azul 394" },
  { label: "Azul GCMI 30", value: "Azul GCMI 30" },
  { label: "Azul GCMI 3086 (VANQUISH)", value: "Azul GCMI 3086 (VANQUISH)" },
  { label: "Azul GCMI 31", value: "Azul GCMI 31" },
  { label: "Azul GCMI 34", value: "Azul GCMI 34" },
  { label: "Azul GCMI 387", value: "Azul GCMI 387" },
  { label: "Azul GCMI 388", value: "Azul GCMI 388" },
  { label: "Azul GCMI 39", value: "Azul GCMI 39" },
  { label: "Azul GCMI 453", value: "Azul GCMI 453" },
  { label: "Azul PMS 291 U", value: "Azul PMS 291 U" },
  { label: "Blanco GCMI 91", value: "Blanco GCMI 91" },
  { label: "Café 50", value: "Café 50" },
  { label: "Café 523", value: "Café 523" },
  { label: "Café GCMI 52", value: "Café GCMI 52" },
  { label: "Gris GCMI 9002", value: "Gris GCMI 9002" },
  { label: "Magenta Valenciana", value: "Magenta Valenciana" },
  { label: "Morado Especial", value: "Morado Especial" },
  { label: "Morado GCMI 267", value: "Morado GCMI 267" },
  { label: "Naranja GCMI 80", value: "Naranja GCMI 80" },
  { label: "Negro (Sánchez)", value: "Negro (Sánchez)" },
  { label: "Purple C", value: "Purple C" },
  { label: "Rojo 74", value: "Rojo 74" },
  { label: "Rojo GCMI 73", value: "Rojo GCMI 73" },
  { label: "Rojo GCMI 75", value: "Rojo GCMI 75" },
  { label: "Rojo GCMI 76", value: "Rojo GCMI 76" },
  { label: "Rojo Patitos", value: "Rojo Patitos" },
  { label: "Rosa 212 U", value: "Rosa 212 U" },
  { label: "Rosa 218", value: "Rosa 218" },
  { label: "Rosa 2365 C (VANE)", value: "Rosa 2365 C (VANE)" },
  { label: "Rosa 918", value: "Rosa 918" },
  { label: "Rosa GCMI 316", value: "Rosa GCMI 316" },
  { label: "Verde 24", value: "Verde 24" },
  { label: "Verde 375", value: "Verde 375" },
  { label: "Verde GCMI 20", value: "Verde GCMI 20" },
  { label: "Verde GCMI 21", value: "Verde GCMI 21" },
  { label: "Verde GCMI 22", value: "Verde GCMI 22" },
  { label: "Verde GCMI 29", value: "Verde GCMI 29" },
  { label: "Verde GCMI Blumen", value: "Verde GCMI Blumen" },
  { label: "Verde GCMI25", value: "Verde GCMI25" },
  { label: "Vino GCMI-LAMOSA", value: "Vino GCMI-LAMOSA" },
  { label: "Violeta 273", value: "Violeta 273" },
  { label: "Violeta Especial", value: "Violeta Especial" },
  { label: "Magenta GCMI 49", value: "Magenta GCMI 49" },
  { label: "Violeta GCMI 984", value: "Violeta GCMI 984" },
  { label: "Violeta Golondrina", value: "Violeta Golondrina" },
  { label: "Verde 3213", value: "Verde 3213" },
  { label: "Azul 325", value: "Azul 325" },
];
